name: Go Build and Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@main
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Build
      run: |
        go get
        go build -v .
        javac reader.java

    - name: Test
      run: |
        ./protoIndexFile
        java ./reader
